version: '3.7'
services:
  mymongodb:
    image: mongo:5.0.6
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
  todoapp:
    image: todoapp
    build: 
      context: TodoApp
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 9090:5100
    links:
      - mymongodb
    depends_on:
      - mymongodb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
